# yamllint disable-file
# Answer file maintained by Copier for: https://github.com/KyleKing/calcipy_template
# Check into version control. Edit by re-running copier and changing responses to the questions
_commit: 0.2.1
_src_path: gh:KyleKing/calcipy_template
author_email: dev.act.kyle@gmail.com
author_name: Kyle King
author_username: kyleking
codecov_token: null
copyright_date: '2021'
doc_dir: docs
install_extras: null
package_name_py: cz_legacy
project_description: Extends Conventional Commits Change Types with User-Defined Legacy
  Types for Commitizen
project_name: cz_legacy
repository_namespace: kyleking
repository_provider: https://github.com
